### ISSUE TITLE
如何复制boot, Magisk, twrp_rec 到 N1？

### ISSUE THREAD

**Issue by ithaibo** [sukanka/NokiaN1Root#1]
在执行完“adb sideload A5CNB19_update.zip”，如何将(boot, Magisk, twrp_rec) 复制到 N1？

**Comment by 18thCentury** [comment]
刷twrp_rec .重启进去,pc上命令行执行 adb push boot.img /sdcard

**Comment by 18thCentury** [comment]
> 
> 
> 在执行完“adb sideload A5CNB19_update.zip”，如何将(boot, Magisk, twrp_rec) 复制到 N1？
刷twrp_rec .重启进去,pc上命令行执行 adb push boot.img /sdcard

**Comment by sukanka** [comment]
> 在执行完“adb sideload A5CNB19_update.zip”，如何将(boot, Magisk, twrp_rec) 复制到 N1？

我不太会用 adb push 之类的, 因此在教程里写的 重启, 在 `adb sideload` 之后应当能够正常启动, 然后开机将文件复制进去.

**Comment by ithaibo** [comment]
adb push 我没有尝试过。但是可以在adb sideload之前，执行fastboot -w。这样可以让不用fastboot oem lock就能进入系统，同时不复制进去的文件
